version: '3'
services:
  jupyterlab_py37_20221101:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab_py37_20221101
    volumes:
      - "./work:/home/work"
      - ".jupyter:/root/.jupyter"
    ports:
      - "8011:8080"
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token=''